tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-container-highest": "#c1ecd4",
                        "primary-fixed": "#b1f0ce",
                        "surface-container-low": "#d1fee5",
                        "on-primary-fixed": "#002114",
                        "on-tertiary-fixed-variant": "#404945",
                        "surface-container": "#ccf8df",
                        "surface-tint": "#2c694e",
                        "outline-variant": "#bfc9c1",
                        "on-tertiary-fixed": "#151d1b",
                        "on-background": "#002114",
                        "on-surface": "#002114",
                        "surface": "#e8fff0",
                        "surface-container-lowest": "#ffffff",
                        "inverse-surface": "#0e3727",
                        "primary-fixed-dim": "#95d4b3",
                        "secondary-fixed": "#8cf9a4",
                        "secondary-fixed-dim": "#70dc8a",
                        "inverse-on-surface": "#cffbe2",
                        "on-primary-fixed-variant": "#0e5138",
                        "on-secondary-fixed": "#00210b",
                        "tertiary": "#414946",
                        "tertiary-container": "#58615d",
                        "outline": "#707973",
                        "inverse-primary": "#95d4b3",
                        "background": "#e8fff0",
                        "tertiary-fixed": "#dce5e0",
                        "on-error": "#ffffff",
                        "surface-variant": "#c1ecd4",
                        "on-tertiary": "#ffffff",
                        "error": "#ba1a1a",
                        "on-secondary-container": "#007235",
                        "on-surface-variant": "#404943",
                        "on-secondary-fixed-variant": "#005224",
                        "secondary": "#006d32",
                        "on-primary-container": "#a8e7c5",
                        "error-container": "#ffdad6",
                        "primary-container": "#2d6a4f",
                        "surface-bright": "#e8fff0",
                        "tertiary-fixed-dim": "#bfc9c4",
                        "on-primary": "#ffffff",
                        "secondary-container": "#89f7a1",
                        "surface-container-high": "#c6f2da",
                        "surface-dim": "#b8e4cc",
                        "on-error-container": "#93000a",
                        "on-secondary": "#ffffff",
                        "primary": "#0f5238",
                        "on-tertiary-container": "#d3dcd7"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "2xl": "1rem",
                        "3xl": "1.5rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "margin-md": "16px",
                        "stack-gap": "24px",
                        "sidebar-width": "280px",
                        "container-padding": "32px",
                        "margin-sm": "8px",
                        "margin-lg": "24px",
                        "gutter": "16px"
                    },
                    "fontFamily": {
                        "headline-xl": ["Plus Jakarta Sans"],
                        "headline-lg-mobile": ["Plus Jakarta Sans"],
                        "body-md": ["Plus Jakarta Sans"],
                        "body-lg": ["Plus Jakarta Sans"],
                        "headline-lg": ["Plus Jakarta Sans"],
                        "label-md": ["Plus Jakarta Sans"],
                        "body-sm": ["Plus Jakarta Sans"],
                        "headline-md": ["Plus Jakarta Sans"]
                    },
                    "fontSize": {
                        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                        "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
                        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
                        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
                    }
                },
            },
        }